//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;


namespace AssemblyCSharp
{
	[Serializable]
	public class MedicationData
	{
		public int numberOfPills;

		public string medicationName;

		public int frequencyByDay;

		public bool periodOfTimeIsImportant;
		public bool needMorning;
		public bool needNoon;
		public bool needEvening;
	}
	
	[Serializable]
	public class PrescriptionData
	{
		public List<MedicationData> listOfMedications;

		public PrescriptionData ()
		{
			listOfMedications = new List<MedicationData> ();
		}

		public void AddMedicationData(string medicationName, int numberOfPills, int frequencyByDay, bool needMorning, bool needNoon, bool needEvening)
		{
			MedicationData medData = new MedicationData ();
			medData.medicationName = medicationName;
			medData.numberOfPills = numberOfPills;
			medData.frequencyByDay = frequencyByDay;
			medData.periodOfTimeIsImportant = needMorning || needNoon || needEvening;
			medData.needMorning = needMorning;
			medData.needNoon = needNoon;
			medData.needEvening = needEvening;
			listOfMedications.Add (medData);
		}
	}
}

