//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;


namespace AssemblyCSharp
{
	public class MedicationData
	{
		public int numberOfPills;

		public string medicationName;

		public int frequencyByDay;

		public bool periodOfTimeIsImportant;
		public bool needMorning;
		public bool needNoon;
		public bool needEvening;
	}

	public class PrescriptionData
	{
		public List<MedicationData> listOfMedication;

		public PrescriptionData ()
		{
		}
	}
}

