// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class Hypochondriax
{
        public const string achievement_remanence = "CgkI6qn1vJsSEAIQAQ"; // <GPGSID>
        public const string achievement_nystagmus = "CgkI6qn1vJsSEAIQAw"; // <GPGSID>
        public const string achievement_visual_snow = "CgkI6qn1vJsSEAIQBg"; // <GPGSID>
        public const string achievement_buphthalmos = "CgkI6qn1vJsSEAIQCw"; // <GPGSID>
        public const string achievement_instagramitis = "CgkI6qn1vJsSEAIQCA"; // <GPGSID>
        public const string leaderboard_days_survived = "CgkI6qn1vJsSEAIQAg"; // <GPGSID>
        public const string achievement_shaking_palsy = "CgkI6qn1vJsSEAIQCQ"; // <GPGSID>
        public const string achievement_scotopic_sensitivity = "CgkI6qn1vJsSEAIQBw"; // <GPGSID>
        public const string achievement_sternutation = "CgkI6qn1vJsSEAIQCg"; // <GPGSID>
        public const string achievement_kinetosis = "CgkI6qn1vJsSEAIQBA"; // <GPGSID>
        public const string achievement_achromatopsia = "CgkI6qn1vJsSEAIQBQ"; // <GPGSID>

}

